---
- name: Resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      ignore_errors: true
      paths:
        - '{{ role_path }}/vars'

# Setup
- include_tasks: setup-Debian.yml
  when:
    - ansible_os_family == 'Debian'

- include_tasks: setup-RedHat.yml
  when:
    - ansible_os_family == 'RedHat'

- name: Create a conda group for multi user install
  group:
    name: "{{ conda_group_name }}"
    gid: "{{ conda_group_gid }}"
    state: present

- name: Change conda permissions
  file:
    path: /opt/conda
    owner: root
    group: "{{ conda_group_name }}"
    mode: '0775'
